### ISSUE TITLE
tab/shell/bash completion

### ISSUE THREAD

**Issue by joker-at-work** [sapcc/limesctl#113]
I'd like to be able to use bash-completion on `limesctl` i.e. pressing tab in my shell to get the commands (and options) autocompleted.

Is there an easy way to add this with a go module or should I start building something for myself?

**Comment by talal** [comment]
@joker-at-work it should be possible to generate completions with the Go library I use. I'll have a look.

**Comment by talal** [comment]
The `limesctl completion` command was added in `v3.1.0`. 

For bash:

```
source <(limesctl completion bash)
```
