### ISSUE TITLE
crash when using an unknown resource name with `limesctl project set`

### ISSUE THREAD

**Issue by majewsky** [sapcc/limesctl#16]
To reproduce, run `limes project set $SOME_PROJECT_ID object-storage/capacity=$SOME_VALUE`. Note that `object-store` is misspelled as `object-storage`. This segfaults for me with the following trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7a50b5]

goroutine 1 [running]:
github.com/sapcc/limesctl/pkg/cli.(*Project).setBaseUnits(0xc0000c2000, 0xc0003f8090, 0xc000121d00)
        /x/src/github.com/sapcc/limesctl/.gopath/src/github.com/sapcc/limesctl/pkg/cli/parse_quotas.go:265 +0x205
github.com/sapcc/limesctl/pkg/cli.ParseRawQuotas(0x923a20, 0xc0000c2000, 0xc00000e9e0, 0x0, 0x0, 0x0, 0x0)
        /x/src/github.com/sapcc/limesctl/.gopath/src/github.com/sapcc/limesctl/pkg/cli/parse_quotas.go:156 +0x5ad
main.main()
        /x/src/github.com/sapcc/limesctl/.gopath/src/github.com/sapcc/limesctl/main.go:253 +0x6ce
```

**Comment by talal** [comment]
As we at one point discussed: this approach of getting information about the specific units for different `service/resource` is futile (as Limes also validates this) for the CLI. The CLI should rather forward the user provided information (service and resource names) as is to Limes' API.

I will refactor the _quota parsing_ logic in favor of a more efficient approach.
