### ISSUE TITLE
cli params for OS_ vars

### ISSUE THREAD

**Issue by viennaa** [sapcc/limesctl#4]
Please add optional cli arguments to specify OS_AUTH_URL, OS_PASSWORD and the other params needed analog to the openstackcli tooling.

Would be great to specify in --help which params are being expected.

**Comment by majewsky** [comment]
Out of curiosity, what is the usecase here? I'm not denying that it's a good idea to be consistent with python-openstackclient here, I'm just wondering why one would need these if you can `export OS_FOO=bar`.

**Comment by viennaa** [comment]
I was sure you would ask and since we talked in person I am just rephrasing here for everyone else:
 
When you are running your OpenStack environment in a docker container you don't have those vars set locally, still, you might want to use `limesctl` locally. Without explicitly exporting all vars one could tinker an alias and specify the params inline.
